package com.example.demo.util;

import java.util.HashMap;
import java.util.Map;

public class CountryCodeMapper {

    private static final Map<String, String> countryCodeMap = new HashMap<>();

    static {
    	countryCodeMap.put("Afghanistan", "af");
        countryCodeMap.put("Albania", "al");
        countryCodeMap.put("Algeria", "dz");
        countryCodeMap.put("Andorra", "ad");
        countryCodeMap.put("Angola", "ao");
        countryCodeMap.put("Antigua and Barbuda", "ag");
        countryCodeMap.put("Argentina", "ar");
        countryCodeMap.put("Armenia", "am");
        countryCodeMap.put("Australia", "au");
        countryCodeMap.put("Austria", "at");
        countryCodeMap.put("Azerbaijan", "az");
        countryCodeMap.put("Bahamas", "bs");
        countryCodeMap.put("Bahrain", "bh");
        countryCodeMap.put("Bangladesh", "bd");
        countryCodeMap.put("Barbados", "bb");
        countryCodeMap.put("Belarus", "by");
        countryCodeMap.put("Belgium", "be");
        countryCodeMap.put("Belize", "bz");
        countryCodeMap.put("Benin", "bj");
        countryCodeMap.put("Bhutan", "bt");
        countryCodeMap.put("Bolivia", "bo");
        countryCodeMap.put("Bosnia and Herzegovina", "ba");
        countryCodeMap.put("Botswana", "bw");
        countryCodeMap.put("Brazil", "br");
        countryCodeMap.put("Brunei", "bn");
        countryCodeMap.put("Bulgaria", "bg");
        countryCodeMap.put("Burkina Faso", "bf");
        countryCodeMap.put("Burma", "mm");
        countryCodeMap.put("Burundi", "bi");
        countryCodeMap.put("Cabo Verde", "cv");
        countryCodeMap.put("Cambodia", "kh");
        countryCodeMap.put("Cameroon", "cm");
        countryCodeMap.put("Canada", "ca");
        countryCodeMap.put("Central African Republic", "cf");
        countryCodeMap.put("Chad", "td");
        countryCodeMap.put("Chile", "cl");
        countryCodeMap.put("China", "cn");
        countryCodeMap.put("Colombia", "co");
        countryCodeMap.put("Comoros", "km");
        countryCodeMap.put("Congo (Brazzaville)", "cg");
        countryCodeMap.put("Congo (Kinshasa)", "cd");
        countryCodeMap.put("Costa Rica", "cr");
        countryCodeMap.put("Cote d'Ivoire", "ci");
        countryCodeMap.put("Croatia", "hr");
        countryCodeMap.put("Cuba", "cu");
        countryCodeMap.put("Cyprus", "cy");
        countryCodeMap.put("Czechia", "cz");
        countryCodeMap.put("Denmark", "dk");
        countryCodeMap.put("Djibouti", "dj");
        countryCodeMap.put("Dominica", "dm");
        countryCodeMap.put("Dominican Republic", "do");
        countryCodeMap.put("Ecuador", "ec");
        countryCodeMap.put("Egypt", "eg");
        countryCodeMap.put("El Salvador", "sv");
        countryCodeMap.put("Equatorial Guinea", "gq");
        countryCodeMap.put("Eritrea", "er");
        countryCodeMap.put("Estonia", "ee");
        countryCodeMap.put("Eswatini", "sz");
        countryCodeMap.put("Ethiopia", "et");
        countryCodeMap.put("Fiji", "fj");
        countryCodeMap.put("Finland", "fi");
        countryCodeMap.put("France", "fr");
        countryCodeMap.put("Gabon", "ga");
        countryCodeMap.put("Gambia", "gm");
        countryCodeMap.put("Georgia", "ge");
        countryCodeMap.put("Germany", "de");
        countryCodeMap.put("Ghana", "gh");
        countryCodeMap.put("Greece", "gr");
        countryCodeMap.put("Grenada", "gd");
        countryCodeMap.put("Guatemala", "gt");
        countryCodeMap.put("Guinea", "gn");
        countryCodeMap.put("Guinea-Bissau", "gw");
        countryCodeMap.put("Guyana", "gy");
        countryCodeMap.put("Haiti", "ht");
        countryCodeMap.put("Holy See", "va");
        countryCodeMap.put("Honduras", "hn");
        countryCodeMap.put("Hungary", "hu");
        countryCodeMap.put("Iceland", "is");
        countryCodeMap.put("India", "in");
        countryCodeMap.put("Indonesia", "id");
        countryCodeMap.put("Iran", "ir");
        countryCodeMap.put("Iraq", "iq");
        countryCodeMap.put("Ireland", "ie");
        countryCodeMap.put("Israel", "il");
        countryCodeMap.put("Italy", "it");
        countryCodeMap.put("Jamaica", "jm");
        countryCodeMap.put("Japan", "jp");
        countryCodeMap.put("Jordan", "jo");
        countryCodeMap.put("Kazakhstan", "kz");
        countryCodeMap.put("Kenya", "ke");
        countryCodeMap.put("Kiribati", "ki");
        countryCodeMap.put("Korea, North", "kp");
        countryCodeMap.put("Korea, South", "kr");
        countryCodeMap.put("Kosovo", "xk");
        countryCodeMap.put("Kuwait", "kw");
        countryCodeMap.put("Kyrgyzstan", "kg");
        countryCodeMap.put("Laos", "la");
        countryCodeMap.put("Latvia", "lv");
        countryCodeMap.put("Lebanon", "lb");
        countryCodeMap.put("Lesotho", "ls");
        countryCodeMap.put("Liberia", "lr");
        countryCodeMap.put("Libya", "ly");
        countryCodeMap.put("Liechtenstein", "li");
        countryCodeMap.put("Lithuania", "lt");
        countryCodeMap.put("Luxembourg", "lu");
        countryCodeMap.put("Madagascar", "mg");
        countryCodeMap.put("Malawi", "mw");
        countryCodeMap.put("Malaysia", "my");
        countryCodeMap.put("Maldives", "mv");
        countryCodeMap.put("Mali", "ml");
        countryCodeMap.put("Malta", "mt");
        countryCodeMap.put("Marshall Islands", "mh");
        countryCodeMap.put("Mauritania", "mr");
        countryCodeMap.put("Mauritius", "mu");
        countryCodeMap.put("Mexico", "mx");
        countryCodeMap.put("Micronesia", "fm");
        countryCodeMap.put("Moldova", "md");
        countryCodeMap.put("Monaco", "mc");
        countryCodeMap.put("Mongolia", "mn");
        countryCodeMap.put("Montenegro", "me");
        countryCodeMap.put("Morocco", "ma");
        countryCodeMap.put("Mozambique", "mz");
        countryCodeMap.put("Namibia", "na");
        countryCodeMap.put("Nauru", "nr");
        countryCodeMap.put("Nepal", "np");
        countryCodeMap.put("Netherlands", "nl");
        countryCodeMap.put("New Zealand", "nz");
        countryCodeMap.put("Nicaragua", "ni");
        countryCodeMap.put("Niger", "ne");
        countryCodeMap.put("Nigeria", "ng");
        countryCodeMap.put("North Macedonia", "mk");
        countryCodeMap.put("Norway", "no");
        countryCodeMap.put("Oman", "om");
        countryCodeMap.put("Pakistan", "pk");
        countryCodeMap.put("Palau", "pw");
        countryCodeMap.put("Panama", "pa");
        countryCodeMap.put("Papua New Guinea", "pg");
        countryCodeMap.put("Paraguay", "py");
        countryCodeMap.put("Peru", "pe");
        countryCodeMap.put("Philippines", "ph");
        countryCodeMap.put("Poland", "pl");
        countryCodeMap.put("Portugal", "pt");
        countryCodeMap.put("Qatar", "qa");
        countryCodeMap.put("Romania", "ro");
        countryCodeMap.put("Russia", "ru");
        countryCodeMap.put("Rwanda", "rw");
        countryCodeMap.put("Saint Kitts and Nevis", "kn");
        countryCodeMap.put("Saint Lucia", "lc");
        countryCodeMap.put("Saint Vincent and the Grenadines", "vc");
        countryCodeMap.put("Samoa", "ws");
        countryCodeMap.put("San Marino", "sm");
        countryCodeMap.put("Sao Tome and Principe", "st");
        countryCodeMap.put("Saudi Arabia", "sa");
        countryCodeMap.put("Senegal", "sn");
        countryCodeMap.put("Serbia", "rs");
        countryCodeMap.put("Seychelles", "sc");
        countryCodeMap.put("Sierra Leone", "sl");
        countryCodeMap.put("Singapore", "sg");
        countryCodeMap.put("Slovakia", "sk");
        countryCodeMap.put("Slovenia", "si");
        countryCodeMap.put("Solomon Islands", "sb");
        countryCodeMap.put("Somalia", "so");
        countryCodeMap.put("South Africa", "za");
        countryCodeMap.put("South Sudan", "ss");
        countryCodeMap.put("Spain", "es");
        countryCodeMap.put("Sri Lanka", "lk");
        countryCodeMap.put("Sudan", "sd");
        countryCodeMap.put("Suriname", "sr");
        countryCodeMap.put("Sweden", "se");
        countryCodeMap.put("Switzerland", "ch");
        countryCodeMap.put("Syria", "sy");
        countryCodeMap.put("Taiwan*", "tw");
        countryCodeMap.put("Tajikistan", "tj");
        countryCodeMap.put("Tanzania", "tz");
        countryCodeMap.put("Thailand", "th");
        countryCodeMap.put("Timor-Leste", "tl");
        countryCodeMap.put("Togo", "tg");
        countryCodeMap.put("Tonga", "to");
        countryCodeMap.put("Trinidad and Tobago", "tt");
        countryCodeMap.put("Tunisia", "tn");
        countryCodeMap.put("Turkey", "tr");
        countryCodeMap.put("Tuvalu", "tv");
        countryCodeMap.put("United Arab Emirates", "ae");
        countryCodeMap.put("United Kingdom", "gb");
        countryCodeMap.put("Uruguay", "uy");
        countryCodeMap.put("Uzbekistan", "uz");
        countryCodeMap.put("Vanuatu", "vu");
        countryCodeMap.put("Venezuela", "ve");
        countryCodeMap.put("Vietnam", "vn");
        countryCodeMap.put("West Bank and Gaza", "ps");
        countryCodeMap.put("Yemen", "ye");
        countryCodeMap.put("Zambia", "zm");
        countryCodeMap.put("Zimbabwe", "zw");

        countryCodeMap.put("Antarctica", "aq");
        countryCodeMap.put("Diamond Princess", "dp"); // This is not an actual country code but used for specific cases
        countryCodeMap.put("MS Zaandam", "mz"); // This is not an actual country code but used for specific cases
        countryCodeMap.put("Summer Olympics 2020", "ol"); // This is not an actual country code but used for specific cases
        countryCodeMap.put("Uganda", "ug");
        countryCodeMap.put("Ukraine", "ua");
        countryCodeMap.put("Winter Olympics 2022", "wo"); // This is not an actual country code but used for specific cases
    }

    public static String getCountryCode(String countryName) {
        return countryCodeMap.getOrDefault(countryName, "unknown");
    }
}
